### ISSUE TITLE
Functionality of text to speech using pyttsx3

### ISSUE THREAD

**Issue by Devansh2005** [Devansh2005/Text-Editor#1]

**Comment by Devansh2005** [comment]
import pyttsx3
speaker =pyttsx3.init()
speaker.say("text_file")
speaker.runAndWait()

**Comment by iriyagupta** [comment]
@Devansh2005 Hi, are we not looking for Linux based programs?

**Comment by Devansh2005** [comment]
For the time ,"No". But if you can add something better to the code with the enhancing its features, you are most welcome @iriyagupta .

**Comment by GC2002** [comment]
I can do it without pyttsx3. please assign.

**Comment by GC2002** [comment]
I can do it with pyttsx3 as well.

**Comment by Devansh2005** [comment]
Sure @GC2002 .

**Comment by GC2002** [comment]
which one do you want? with or without?

**Comment by Devansh2005** [comment]
Try it with which you are comfortable. Do add a button to play the written text.

**Comment by GC2002** [comment]
Oh you want a button? it's alright will just add it. give me a moment
