### ISSUE TITLE
Add a requirement.txt file in the repo.

### ISSUE THREAD

**Issue by Devansh2005** [Devansh2005/Text-Editor#33]
Also update it it readme.md file

**Comment by georgioupanayiotis** [comment]
@Devansh2005 can you assign me this task ?

**Comment by Devansh2005** [comment]
Ok @georgioupanayiotis .

**Comment by georgioupanayiotis** [comment]
> Also update it it readme.md file

what do i need to add ?

**Comment by georgioupanayiotis** [comment]
@Devansh2005 created the PR https://github.com/Devansh2005/Text-Editor/pull/34

**Comment by Devansh2005** [comment]
@georgioupanayiotis check out the PR. I have added a comment what to do. Good luck.

**Comment by Devansh2005** [comment]
https://blog.usejournal.com/why-and-how-to-make-a-requirements-txt-f329c685181e. The good source for you to know about it. If you are just here for hacktoberfest label , do let me know. I'll give that too.

**Comment by er-raoniz** [comment]
@Devansh2005 - If this is still open, can quickly fix and create a PR. (need for hactoberfest'20 :P)

**Comment by Devansh2005** [comment]
sure @er-raoniz .Do it.

**Comment by adhilcodes** [comment]
I would like to fix it , please assign me and help me to fix it

**Comment by Devansh2005** [comment]
You can read the article. It is completely ok if you aren't able to do it. Create a branch a mess up with it. Don't be afraid of making the mistakes. If you 1% of it that is also useful @adhilcodes .

**Comment by adhilcodes** [comment]
> You can read the article. It is completely ok if you aren't able to do it. Create a branch a mess up with it. Don't be afraid of making the mistakes. If you 1% of it that is also useful @adhilcodes .

I have created a PR by adding **requirements,txt file** . Let me know how to improve it

**Comment by Devansh2005** [comment]
I have merged the PR making some changes in it. If you want it for hacktober let me know, I'll mark the label.

**Comment by adhilcodes** [comment]
> I have merged the PR making some changes in it. If you want it for hacktober let me know, I'll mark the label.

Yeah... Label it for hacktoberfest
