### ISSUE TITLE
Functionality for Speech to Text

### ISSUE THREAD

**Issue by haelmj** [Devansh2005/Text-Editor#40]
Possibly using google [speech recognition](https://pypi.org/project/SpeechRecognition/) module.

**Comment by Devansh2005** [comment]
Frankly speaking I'm not able to Implement it. I was trying it as you can see in folder text_to_speech. I'll also look into [speech recognition](https://pypi.org/project/SpeechRecognition) module.

**Comment by haelmj** [comment]
I can attempt implementing text to speech using pyttsx3 and then subsequently speech to text with Speech Recognition module. Hopefully, next week.

**Comment by Devansh2005** [comment]
Best of Luck @haelmj ! You're most welcome and thank you in advance for this help.

**Comment by haelmj** [comment]
I was able to get the *text to speech* functionality working. I've sent a pull request. I'm still working on the *speech to text* functionality.

**Comment by Devansh2005** [comment]
This is too good man ! Let's connect.
