### ISSUE TITLE
Bug: Italic button not working correctly

### ISSUE THREAD

**Issue by haelmj** [Devansh2005/Text-Editor#50]
# Problem
When Italics button is clicked, text changes to italics font. However, if text is already in italics format, clicking the button does nothing.

## Expected Result
Text changes back to normal font.

## Solution
In dpad.py replace `weight` on line 188 with `slant`

**Comment by er-raoniz** [comment]
@Devansh2005 @haelmj  - Please assign me this issue. I can close this quickly with mentioned solution, need it for Hactoberfest'20! :P

**Comment by Devansh2005** [comment]
`You're assigned`@er-roniz

**Comment by er-raoniz** [comment]
created PR #51 to fix this, please review and merge.
also, do add hacktoberfest label! :P
