### ISSUE TITLE
Updating README

### ISSUE THREAD

**Issue by haelmj** [Devansh2005/Text-Editor#54]
I think the contribution section on the readme needs to be updated since the suggested feature has already been implemented

**Comment by aia7k7k** [comment]
Hi, I am a beginner and I want to try contributing to this issue. 
Should I just delete that line entirely, or should I replace it with another possible feature?

**Comment by haelmj** [comment]
@aia7k7k You can do both if you'd like. Take off the existing suggested feature and add a new one. If you are thinking of possible features then you can also ask @Devansh2005 what ideas he wants to see.

**Comment by aia7k7k** [comment]
Thanks! @Devansh2005 Can you please suggest some features that I can put up there? Since I am new to this, I don't want to arbitrarily make up some features that could end up being irrelevant to the project.

**Comment by Devansh2005** [comment]
@aia7k7k  we can discuss what all ideas you have. Nothing is irrelevant @aia7k7k . Try to implement any of the feature that you can add, and don't worry that you are doing something wrong, instead you are learning something.

**Comment by aia7k7k** [comment]
Alright.
